<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>io.github.czelabueno</groupId>
  <artifactId>jai-workflow-langchain4j-moa</artifactId>
  <version>0.1.0</version>
  <packaging>jar</packaging>

  <name>jAI Workflow :: LangChain4j :: Mixture of Agents</name>
  <description>Java implementation of MoA AI paper https://arxiv.org/pdf/2406.04692</description>

  <properties>
    <jai.workflow.version>0.3.0</jai.workflow.version>
    <langchain4j.version>1.0.0-alpha1</langchain4j.version>
  </properties>

  <dependencies>
    <dependency>
      <groupId>io.github.czelabueno</groupId>
      <artifactId>jai-workflow-langchain4j</artifactId>
      <version>${jai.workflow.version}</version>
    </dependency>

    <!-- Default LLMs -->
    <dependency>
      <groupId>dev.langchain4j</groupId>
      <artifactId>langchain4j-mistral-ai</artifactId>
      <version>${langchain4j.version}</version>
      <scope>test</scope>
    </dependency>

    <dependency>
      <groupId>dev.langchain4j</groupId>
      <artifactId>langchain4j-community-dashscope</artifactId>
      <version>${langchain4j.version}</version>
      <scope>test</scope>
    </dependency>

    <dependency>
      <groupId>dev.langchain4j</groupId>
      <artifactId>langchain4j-anthropic</artifactId>
      <version>${langchain4j.version}</version>
      <scope>test</scope>
    </dependency>

    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-engine</artifactId>
      <version>5.10.0</version>
      <scope>test</scope>
    </dependency>

    <dependency>
      <groupId>org.assertj</groupId>
      <artifactId>assertj-core</artifactId>
      <version>3.24.2</version>
      <scope>test</scope>
    </dependency>

    <dependency>
      <groupId>io.projectreactor</groupId>
      <artifactId>reactor-test</artifactId>
      <version>3.7.0</version>
      <scope>test</scope>
    </dependency>

    <dependency>
      <groupId>org.tinylog</groupId>
      <artifactId>tinylog-impl</artifactId>
      <version>2.6.2</version>
    </dependency>

    <dependency>
      <groupId>org.tinylog</groupId>
      <artifactId>slf4j-tinylog</artifactId>
      <version>2.6.2</version>
    </dependency>

  </dependencies>
</project>
